import type { Metadata } from "next";
import { Abel } from 'next/font/google'
import '../styles/globals.css';
import '../styles';

const roboto = Abel({
  weight: '400',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <title>Metaverse</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    
      <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
      </head>
      <body className={roboto.className}>
        
        {
      
      children
      }</body>
    </html>
  );
}
