export const eventsData = [{
        id: 'event-1',
        eventName: 'Magical Night Gala',
        description: 'A magical night filled with enchanting experiences and surprises.',
        location: 'Wizardry Hall, Hogwarts',
        price: '$50.00',
        date: '2024-02-15',
        organizerName: 'Hogwarts Events Committee',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-2',
        eventName: 'Stranger Things Marathon',
        description: 'An immersive journey into the world of the Upside Down with a Stranger Things marathon.',
        location: 'Hawkins Community Center',
        price: '$20.00',
        date: '2024-03-10',
        organizerName: 'Hawkins Events Society',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-3',
        eventName: 'Kadirojo Night Market',
        description: 'Explore the vibrant Kadirojo Night Market with various stalls and cultural performances.',
        location: 'Kadirojo Permai Square',
        price: 'Free Admission',
        date: '2024-04-05',
        organizerName: 'Kadirojo Community Events',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-4',
        eventName: 'Island Paradise Retreat',
        description: 'Relax and unwind in a paradise island retreat with breathtaking views.',
        location: 'Paradise Island Resort',
        price: '$150.00',
        date: '2024-05-20',
        organizerName: 'Island Events Co.',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-5',
        eventName: 'Hawkins Labs Science Fair',
        description: 'Discover the wonders of science at the Hawkins Labs Science Fair.',
        location: 'Hawkins Labs Auditorium',
        price: '$30.00',
        date: '2024-06-15',
        organizerName: 'Hawkins Labs Society',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-6',
        eventName: 'Enchanted Forest Ball',
        description: 'Step into a mystical world at the Enchanted Forest Ball filled with enchanting experiences and surprises.',
        location: 'Fairy Glen Pavilion',
        price: '$55.00',
        date: '2024-07-25',
        organizerName: 'Mystical Events Society',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-7',
        eventName: 'Seaside Music Festival',
        description: 'Immerse yourself in a day of live music and seaside vibes at the Seaside Music Festival.',
        location: 'Sunny Shores Amphitheater',
        price: '$25.00',
        date: '2024-08-12',
        organizerName: 'Coastal Events',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-8',
        eventName: 'Harvest Moon Dinner',
        description: 'Savor an exquisite dining experience under the harvest moon at the Harvest Moon Dinner.',
        location: 'Rustic Farmstead',
        price: '$75.00',
        date: '2024-09-19',
        organizerName: 'Gastronomic Affairs Company',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-9',
        eventName: 'Masquerade Charity Ball',
        description: 'Join the glamorous Masquerade Charity Ball for a night of elegance and charitable giving.',
        location: 'Grandiose Ballroom',
        price: '$100.00',
        date: '2024-10-28',
        organizerName: 'Philanthropy Events Organization',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-11',
        eventName: 'Midsummer Masquerade Ball',
        description: 'Experience an enchanting night of mystery and romance at the Midsummer Masquerade Ball.',
        location: 'Fairytale Manor',
        price: '$60.00',
        date: '2024-07-14',
        organizerName: 'Enchanted Events Agency',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-12',
        eventName: 'Galactic Star Cruise',
        description: 'Embark on an intergalactic journey aboard the luxurious Galactic Star Cruise.',
        location: 'Spaceport Alpha 3',
        price: '$200.00',
        date: '2024-08-30',
        organizerName: 'Cosmic Travel Agency',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-13',
        eventName: 'Carnival Extravaganza',
        description: 'Enjoy a day of fun, games, and festivities at the colorful Carnival Extravaganza.',
        location: 'Springfield Park',
        price: 'Free Admission',
        date: '2024-09-22',
        organizerName: 'Springfield Community Events',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-14',
        eventName: 'Sunset Yoga Retreat',
        description: 'Connect with nature and find inner peace during the Sunset Yoga Retreat by the beach.',
        location: 'Tranquil Shores Resort',
        price: '$40.00',
        date: '2024-10-18',
        organizerName: 'Zen Wellness Center',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-15',
        eventName: 'Winter Wonderland Festival',
        description: 'Delight in the magic of the season at the Winter Wonderland Festival with festive activities and entertainment.',
        location: 'Frosty Meadows Park',
        price: 'Free Admission',
        date: '2024-11-30',
        organizerName: 'Frosty Meadows Events Group',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-16',
        eventName: 'Fairy Tale Ball',
        description: 'Let your imagination come to life at the enchanting Fairy Tale Ball, a night of whimsy and magic.',
        location: 'Enchanted Hall',
        price: '$65.00',
        date: '2025-01-15',
        organizerName: 'Enchanted Events Agency',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-17',
        eventName: 'Northern Lights Expedition',
        description: 'Embark on a journey to witness the mesmerizing Northern Lights in all their glory.',
        location: 'Arctic Wilderness Lodge',
        price: '$180.00',
        date: '2025-02-28',
        organizerName: 'Aurora Expeditions Co.',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-18',
        eventName: 'Spring Equinox Celebration',
        description: 'Celebrate the arrival of spring with a festive gathering of music, dance, and nature.',
        location: 'Verdant Meadows Park',
        price: 'Free Admission',
        date: '2025-03-20',
        organizerName: 'Springtide Events Group',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-19',
        eventName: 'Safari Sunset Safari Sunset',
        description: 'Experience the breathtaking beauty of a sunset on the savannah on a safari adventure.',
        location: 'Serengeti National Park',
        price: '$90.00',
        date: '2025-04-25',
        organizerName: 'Safari Adventures Ltd.',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    },
    {
        id: 'event-20',
        eventName: 'Grand Masquerade Ball',
        description: 'Indulge in an evening of opulence and mystique at the Grand Masquerade Ball.',
        location: 'Opulent Palace',
        price: '$120.00',
        date: '2025-06-05',
        organizerName: 'Opulence Events Corporation',
        img1URL: '/event-20-image1.png',
        img2URL: '/event-20-image2.png'
    }
];