export const eventsData = [
    {
      id: 'event-1',
      eventName: 'Magical Night Gala',
      description: 'A magical night filled with enchanting experiences and surprises.',
      location: 'Wizardry Hall, Hogwarts',
      image1Url: '../public/event1.jpg',
      image2Url: '../public/event2.jpg',
      price: '$50.00',
      date: '2024-02-15',
      organizerName: 'Hogwarts Events Committee',
    },
    {
      id: 'event-2',
      eventName: 'Stranger Things Marathon',
      description: 'An immersive journey into the world of the Upside Down with a Stranger Things marathon.',
      location: 'Hawkins Community Center',
      image1Url: '/event-02-image1.png',
      image2Url: '/event-02-image2.png',
      price: '$20.00',
      date: '2024-03-10',
      organizerName: 'Hawkins Events Society',
    },
    {
      id: 'event-3',
      eventName: 'Kadirojo Night Market',
      description: 'Explore the vibrant Kadirojo Night Market with various stalls and cultural performances.',
      location: 'Kadirojo Permai Square',
      image1Url: '/event-03-image1.png',
      image2Url: '/event-03-image2.png',
      price: 'Free Admission',
      date: '2024-04-05',
      organizerName: 'Kadirojo Community Events',
    },
    {
      id: 'event-4',
      eventName: 'Island Paradise Retreat',
      description: 'Relax and unwind in a paradise island retreat with breathtaking views.',
      location: 'Paradise Island Resort',
      image1Url: '/event-04-image1.png',
      image2Url: '/event-04-image2.png',
      price: '$150.00',
      date: '2024-05-20',
      organizerName: 'Island Events Co.',
    },
    {
      id: 'event-5',
      eventName: 'Hawkins Labs Science Fair',
      description: 'Discover the wonders of science at the Hawkins Labs Science Fair.',
      location: 'Hawkins Labs Auditorium',
      image1Url: '/event-05-image1.png',
      image2Url: '/event-05-image2.png',
      price: '$30.00',
      date: '2024-06-15',
      organizerName: 'Hawkins Labs Society',
    },
  ];
  